Assignments/pig latin
bhs-intro-to-programming/Bryan-25 pull request #2
Opened 2022-09-12 22:27 UTC by Bryan-25

2022-09-13 00:48 UTC, gigamonkey requested changes
Can you run the reformatter on this and  maybe fix that variable name and I'll take another look. Thanks!

2022-09-13 00:48 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +const pigLatin = (_fP) =>
Overall this is good. And I liked the history of how you developed it, in pieces, heading toward the final version.

One question: why did you use the variable name `_fP`? What does that stand for? And why the `_` at the front? As a matter of style I strongly prefer short, meaningful words as variable names. Or in some cases, a single letter like `i` for a variable that is going to hold the value of an index. For this variable, I'd probably go with `word` since that's what the value we're supposed to handle is described as being.

2022-09-13 00:48 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +_fP.substring(_fP.search(/[aeiou]/),_fP.length)+
This indentation is a bit wonky. I think right clicking in the editor and choosing "Format document" from the menu that pops up will fix it and show you how it should be formatted.

2022-09-13 00:48 UTC, gigamonkey commented on assignments/pig-latin/code.js
> +_fP.substring(_fP.search(/[aeiou]/),_fP.length)+
Also remember that `substring` can be called with just one argument to extract from a given index all the way to the end, i.e. the second argument is implicitly `_fP.length` if not provided.

2022-09-13 21:41 UTC, Bryan-25 commented on assignments/pig-latin/code.js
> +const pigLatin = (_fP) =>
fP stands for flying Pigs, as for the _ I genuinely didn't know it would work without it.

2022-09-13 21:43 UTC, Bryan-25 commented on assignments/pig-latin/code.js
> +const pigLatin = (_fP) =>
@gigamonkey

2022-09-13 22:03 UTC, merged

2022-09-16 18:18 UTC, gigamonkey commented
So technically you shouldn't have merged this until I had re-reviewed it and approved it. But it looks like you made the requested changes so no big deal. In future though, please wait for the PR to be approved before you merge.